### ISSUE TITLE
Allow no arguments if all values have defaults

### ISSUE THREAD

**Issue by derosm2** [pawurb/smart_init#1]
When using `initialize_with_hash` and having a default for all values, you still would have to send an empty hash to the call method.

Example:
```rb
class Adder < SmartInit::Base
  initialize_with :num_a:1, num_b: 2
  is_callable

  def call
    num_a + num_b
  end
end
```

Expected
```rb
Adder.call => 4
Adder.call({}) => 4
```

Actual
```rb
Adder.call
ArgumentError (invalid input, expected hash of attributes)
```

Ideally you wouldn't have to pass in an empty hash if all the values have defaults.

**Comment by pawurb** [comment]
Thanks for spotting it. Has been fixed and released as 3.4.0.
