### ISSUE TITLE
proposing a `public_accessors: true` option

### ISSUE THREAD

**Issue by morgvanny** [pawurb/smart_init#4]
This could be nice to have, just to be able to create POROs that fully expose readers and writers for all of the same variables that it's initialized with. Currently, the simplest way I can think to do that looks like this:
```
class Thing
  extend SmartInit
  attrs = %i[name color description]
  initialize_with *attrs, public_readers: true
  attr_writer *attrs
end
```
I'd like to be able to just change `public_readers` to `public_accessors` and omit the final line in the class.

If you aren't opposed to this, I could probably implement it and submit a PR.
Could do public_writers too, but idk if that would be as useful.

**Comment by pawurb** [comment]
Hi. Sure the change sounds sensible, looking forward to the PR. Please make sure to include specs. Also agree that writers alone are not needed.

**Comment by pawurb** [comment]
The change was merged.
